// src/lib/glossary.js
// 100 core crypto terms — expandable to 2000+
// Each term = 1 unique SEO page

export const GLOSSARY_TERMS = [
  { slug: 'blockchain', term: 'Blockchain', category: 'Technology', difficulty: 'Beginner', definition: 'A blockchain is a distributed digital ledger that records transactions across many computers. Each block contains transaction data, a timestamp, and a cryptographic hash of the previous block, making it nearly impossible to alter past records.', longDesc: 'Blockchain technology was first conceptualized by Satoshi Nakamoto in 2008 as the underlying technology for Bitcoin. It works as a chain of blocks where each block stores a batch of valid transactions. The decentralized nature means no single entity controls the data. Blockchains can be public (like Bitcoin and Ethereum), private (used by enterprises), or consortium (shared between organizations). The immutability of blockchain makes it ideal for financial transactions, supply chain management, voting systems, and digital identity verification.', related: ['bitcoin', 'ethereum', 'decentralization', 'consensus-mechanism', 'smart-contract'], coins: ['bitcoin', 'ethereum'] },

  { slug: 'bitcoin', term: 'Bitcoin', category: 'Cryptocurrency', difficulty: 'Beginner', definition: 'Bitcoin (BTC) is the first and largest cryptocurrency by market cap. Created in 2009 by the anonymous Satoshi Nakamoto, it enables peer-to-peer transactions without intermediaries using blockchain technology.', longDesc: 'Bitcoin was launched in January 2009 with the mining of the genesis block. It has a fixed maximum supply of 21 million coins, making it deflationary by design. Bitcoin uses a Proof of Work consensus mechanism where miners compete to validate transactions. Bitcoin halving events occur every 4 years, reducing the block reward by 50%. The Bitcoin network processes approximately 7 transactions per second. It is considered digital gold and a store of value by many institutional investors.', related: ['blockchain', 'mining', 'halving', 'satoshi', 'proof-of-work'], coins: ['bitcoin'] },

  { slug: 'ethereum', term: 'Ethereum', category: 'Cryptocurrency', difficulty: 'Beginner', definition: 'Ethereum is a decentralized blockchain platform that enables smart contracts and decentralized applications (dApps). Its native currency is Ether (ETH). Founded by Vitalik Buterin in 2015.', longDesc: 'Ethereum expanded on Bitcoin\'s concept by introducing a programmable blockchain. Smart contracts on Ethereum automatically execute when predefined conditions are met. The Ethereum network transitioned from Proof of Work to Proof of Stake in September 2022 (The Merge), reducing energy consumption by 99.95%. Ethereum is the foundation for DeFi, NFTs, and most Web3 applications. ETH is used to pay gas fees for all transactions on the network.', related: ['smart-contract', 'defi', 'nft', 'gas-fee', 'proof-of-stake'], coins: ['ethereum'] },

  { slug: 'defi', term: 'DeFi (Decentralized Finance)', category: 'Finance', difficulty: 'Intermediate', definition: 'DeFi refers to financial services built on blockchain networks that operate without centralized intermediaries like banks. Users can lend, borrow, trade, and earn interest using smart contracts.', longDesc: 'Decentralized Finance (DeFi) replicates traditional financial services on blockchain networks. DeFi protocols include decentralized exchanges (DEXs) like Uniswap, lending platforms like Aave and Compound, yield farming protocols, and stablecoins. The total value locked (TVL) in DeFi peaked at over $180 billion in 2021. DeFi offers permissionless access — anyone with an internet connection and a crypto wallet can participate. Key risks include smart contract bugs, liquidation risk, and impermanent loss.', related: ['smart-contract', 'yield-farming', 'liquidity-pool', 'dex', 'stablecoin'], coins: ['uniswap', 'aave', 'compound'] },

  { slug: 'nft', term: 'NFT (Non-Fungible Token)', category: 'Digital Assets', difficulty: 'Beginner', definition: 'An NFT is a unique digital asset verified on a blockchain. Unlike regular cryptocurrencies, each NFT is one-of-a-kind and cannot be replicated or exchanged on a 1:1 basis.', longDesc: 'Non-fungible tokens represent ownership of unique digital or physical items. They are most commonly used for digital art, music, gaming items, and collectibles. NFTs are primarily built on Ethereum using the ERC-721 standard. The NFT market exploded in 2021 with Bored Ape Yacht Club, CryptoPunks, and digital artist Beeple selling an NFT for $69 million. NFT metadata is stored on IPFS or directly on-chain. While the market has cooled since 2021, NFTs continue to find utility in gaming, ticketing, and real-world asset tokenization.', related: ['ethereum', 'smart-contract', 'metaverse', 'web3', 'digital-ownership'], coins: ['ethereum', 'solana'] },

  { slug: 'smart-contract', term: 'Smart Contract', category: 'Technology', difficulty: 'Intermediate', definition: 'A smart contract is a self-executing program stored on a blockchain that automatically runs when predetermined conditions are met — no middlemen required.', longDesc: 'Smart contracts were first proposed by Nick Szabo in 1994, but became practical with Ethereum in 2015. They are written in programming languages like Solidity (Ethereum) or Rust (Solana). Once deployed, smart contracts are immutable and transparent — anyone can verify their code. They power DeFi protocols, NFT marketplaces, DAOs, and token launches. Major smart contract platforms include Ethereum, Solana, Cardano, Polkadot, and Avalanche. Security audits are critical as bugs can lead to millions in losses (e.g., the DAO hack of 2016).', related: ['ethereum', 'solidity', 'defi', 'dao', 'blockchain'], coins: ['ethereum', 'solana', 'cardano'] },

  { slug: 'proof-of-work', term: 'Proof of Work (PoW)', category: 'Consensus', difficulty: 'Intermediate', definition: 'Proof of Work is a consensus mechanism where miners solve complex mathematical puzzles to validate transactions and create new blocks. Used by Bitcoin.', longDesc: 'Proof of Work was invented by Cynthia Dwork and Moni Naor in 1993 and later adapted by Satoshi Nakamoto for Bitcoin. Miners compete to solve SHA-256 cryptographic puzzles. The first to solve it gets to add the next block and receives a block reward. PoW is energy-intensive — Bitcoin consumes more electricity than some countries. The difficulty adjusts every 2016 blocks to maintain a 10-minute block time. PoW provides strong security through computational cost — attacking the network would require controlling 51% of hash power.', related: ['mining', 'bitcoin', 'hash-rate', 'proof-of-stake', '51-percent-attack'], coins: ['bitcoin'] },

  { slug: 'proof-of-stake', term: 'Proof of Stake (PoS)', category: 'Consensus', difficulty: 'Intermediate', definition: 'Proof of Stake is an energy-efficient consensus mechanism where validators lock up (stake) cryptocurrency as collateral to validate transactions and earn rewards.', longDesc: 'Proof of Stake was proposed as a greener alternative to Proof of Work. Validators are chosen to create new blocks based on the amount of cryptocurrency they stake. Ethereum switched to PoS in September 2022, reducing energy use by 99.95%. To become an Ethereum validator, you need to stake 32 ETH. Slashing is a penalty mechanism that destroys part of a validator\'s stake for malicious behavior. Variations include Delegated Proof of Stake (DPoS) used by EOS and Tron, and Nominated PoS used by Polkadot.', related: ['staking', 'validator', 'ethereum', 'slashing', 'proof-of-work'], coins: ['ethereum', 'cardano', 'solana'] },

  { slug: 'wallet', term: 'Crypto Wallet', category: 'Tools', difficulty: 'Beginner', definition: 'A crypto wallet is a software or hardware tool that stores private and public keys, enabling users to send, receive, and manage their cryptocurrency holdings.', longDesc: 'Crypto wallets don\'t actually store coins — they store the private keys that prove ownership of coins on the blockchain. Hot wallets (software wallets like MetaMask, Trust Wallet) are connected to the internet and convenient but less secure. Cold wallets (hardware wallets like Ledger, Trezor) store keys offline and are the most secure option. Custodial wallets (exchange wallets) are managed by a third party — not recommended for large holdings. Seed phrases (12-24 words) are the master backup for all wallets — never share them with anyone.', related: ['private-key', 'seed-phrase', 'metamask', 'cold-storage', 'exchange'], coins: [] },

  { slug: 'staking', term: 'Staking', category: 'Finance', difficulty: 'Beginner', definition: 'Staking involves locking up cryptocurrency in a blockchain network to support operations like transaction validation. In return, stakers earn rewards — similar to earning interest.', longDesc: 'Staking is the process of participating in a Proof of Stake blockchain by locking tokens to help validate transactions. Annual staking rewards (APY) vary by network: Ethereum ~4%, Solana ~7%, Cardano ~4%, Cosmos ~14%. Liquid staking protocols like Lido allow stakers to receive liquid tokens (stETH) representing their staked ETH, which can be used in DeFi. Risks include lockup periods, slashing penalties, and the volatility of the staked asset. Staking income may be taxable depending on jurisdiction.', related: ['proof-of-stake', 'validator', 'yield', 'defi', 'apy'], coins: ['ethereum', 'solana', 'cardano'] },

  { slug: 'altcoin', term: 'Altcoin', category: 'Cryptocurrency', difficulty: 'Beginner', definition: 'Altcoin refers to any cryptocurrency other than Bitcoin. The term combines "alternative" and "coin." Thousands of altcoins exist, ranging from Ethereum to meme coins.', longDesc: 'The term altcoin was first used when Litecoin launched in 2011 as the first alternative to Bitcoin. Altcoins are generally classified into: utility tokens (used within platforms), security tokens (represent asset ownership), stablecoins (pegged to fiat), meme coins (community-driven), and DeFi tokens. Most altcoins follow Bitcoin\'s price movements — when BTC rises, altcoins typically rise more (higher beta). Altcoin season refers to periods when altcoins outperform Bitcoin. Small-cap altcoins carry higher risk but also potentially higher reward.', related: ['bitcoin', 'token', 'meme-coin', 'market-cap', 'altcoin-season'], coins: ['ethereum', 'solana', 'cardano'] },

  { slug: 'stablecoin', term: 'Stablecoin', category: 'Cryptocurrency', difficulty: 'Beginner', definition: 'A stablecoin is a cryptocurrency designed to maintain a stable value, typically pegged to a fiat currency like the US dollar. Examples include USDT, USDC, and DAI.', longDesc: 'Stablecoins solve the volatility problem of cryptocurrencies. They come in three main types: fiat-backed (USDT, USDC — backed by actual dollars in bank accounts), crypto-backed (DAI — backed by overcollateralized crypto), and algorithmic (like the failed UST/Luna — maintained by algorithms). Tether (USDT) is the largest stablecoin with a $80+ billion market cap. Stablecoins are essential for DeFi — they allow users to trade and earn yield without exposure to volatility. Regulatory scrutiny of stablecoins has increased significantly since 2022.', related: ['tether', 'usdc', 'dai', 'defi', 'peg'], coins: ['tether', 'usd-coin', 'dai'] },

  { slug: 'gas-fee', term: 'Gas Fee', category: 'Technology', difficulty: 'Beginner', definition: 'Gas fees are transaction fees paid to blockchain validators/miners for processing transactions. On Ethereum, fees are denominated in Gwei (a fraction of ETH).', longDesc: 'Gas on Ethereum measures the computational work required to execute transactions or smart contracts. Gas price is set by users (higher gas = faster processing). During network congestion, gas fees can spike dramatically — sometimes costing more than the transaction itself. Ethereum\'s EIP-1559 upgrade introduced a base fee that is burned plus a priority tip for validators. Layer 2 solutions like Arbitrum and Optimism reduce gas costs by 10-100x. Alternative blockchains like Solana and BSC offer much lower fees — fractions of a cent.', related: ['ethereum', 'gwei', 'layer-2', 'eip-1559', 'transaction'], coins: ['ethereum'] },

  { slug: 'mining', term: 'Crypto Mining', category: 'Technology', difficulty: 'Intermediate', definition: 'Cryptocurrency mining is the process of using computing power to solve cryptographic puzzles, validate transactions, and add new blocks to the blockchain — earning new coins as reward.', longDesc: 'Mining was the original way to earn cryptocurrency, starting with Bitcoin in 2009. Miners use specialized hardware (ASICs for Bitcoin, GPUs for Ethereum before The Merge) to compete in solving SHA-256 puzzles. Mining profitability depends on coin price, electricity cost, hardware efficiency, and network difficulty. The Bitcoin halving every 4 years cuts the block reward by 50% — from 50 BTC (2009) to 3.125 BTC (2024). Mining pools allow small miners to combine hash power and share rewards. Bitcoin mining consumes ~120 TWh of electricity annually.', related: ['proof-of-work', 'hash-rate', 'asic', 'mining-pool', 'halving'], coins: ['bitcoin'] },

  { slug: 'dex', term: 'DEX (Decentralized Exchange)', category: 'Finance', difficulty: 'Intermediate', definition: 'A DEX is a cryptocurrency exchange that operates without a central authority, using smart contracts and liquidity pools to enable peer-to-peer trading directly from users\' wallets.', longDesc: 'Decentralized exchanges like Uniswap, SushiSwap, and PancakeSwap use Automated Market Maker (AMM) models instead of traditional order books. Liquidity providers deposit token pairs into pools and earn trading fees. The first successful DEX, EtherDelta, launched in 2016. Uniswap V3 introduced concentrated liquidity, making capital more efficient. DEXs do not require KYC, giving users full custody of their funds. Disadvantages include higher gas fees, slippage on large trades, and MEV (Miner Extractable Value) attacks.', related: ['amm', 'liquidity-pool', 'uniswap', 'defi', 'yield-farming'], coins: ['uniswap'] },

  { slug: 'halving', term: 'Bitcoin Halving', category: 'Bitcoin', difficulty: 'Intermediate', definition: 'Bitcoin halving is an event that occurs every 210,000 blocks (~4 years) where the block reward for miners is cut in half. It reduces the rate of new Bitcoin supply.', longDesc: 'Satoshi Nakamoto programmed halvings to control Bitcoin\'s inflation. The halvings occurred in 2012 (50→25 BTC), 2016 (25→12.5 BTC), 2020 (12.5→6.25 BTC), and April 2024 (6.25→3.125 BTC). The final Bitcoin will be mined around 2140. Historically, Bitcoin\'s price has surged in the 12-18 months following a halving. After the last Bitcoin is mined, miners will be compensated solely through transaction fees. The halvings are automatically enforced by the Bitcoin protocol.', related: ['bitcoin', 'mining', 'proof-of-work', 'supply', 'block-reward'], coins: ['bitcoin'] },

  { slug: 'dao', term: 'DAO (Decentralized Autonomous Organization)', category: 'Governance', difficulty: 'Advanced', definition: 'A DAO is an organization governed by smart contracts and token holders rather than traditional management. Members vote on proposals using governance tokens.', longDesc: 'DAOs represent a new form of organization that is transparent, community-governed, and operates on blockchain. The first major DAO ("The DAO") was launched on Ethereum in 2016, raising $150M before being hacked. Modern DAOs include Uniswap DAO (governing the DEX), MakerDAO (managing DAI stablecoin), and ConstitutionDAO (raised $47M to buy a copy of the US Constitution). DAO governance typically involves creating proposals, community discussion, and on-chain voting weighted by token holdings. Legal recognition of DAOs is emerging — Wyoming, USA was first to legally recognize DAOs in 2021.', related: ['governance-token', 'smart-contract', 'voting', 'defi', 'web3'], coins: ['uniswap', 'maker'] },

  { slug: 'web3', term: 'Web3', category: 'Technology', difficulty: 'Beginner', definition: 'Web3 is the next evolution of the internet, built on blockchain technology. It aims to give users control over their data and digital assets, without relying on centralized platforms.', longDesc: 'Web3 contrasts with Web1 (read-only static websites) and Web2 (interactive but centralized platforms like Facebook and Google). Web3 applications (dApps) run on decentralized networks, giving users ownership of their data and digital assets. Key components include cryptocurrencies, NFTs, DAOs, DeFi, and decentralized storage (IPFS, Arweave). Critics argue Web3 is currently slow, expensive, and difficult to use compared to Web2. Major Web3 infrastructure projects include Ethereum, Polkadot, and Solana. The term was coined by Ethereum co-founder Gavin Wood in 2014.', related: ['blockchain', 'dapp', 'nft', 'defi', 'dao'], coins: ['ethereum', 'polkadot'] },

  { slug: 'market-cap', term: 'Market Capitalization', category: 'Finance', difficulty: 'Beginner', definition: 'Crypto market cap = current price × circulating supply. It measures the total value of a cryptocurrency and is used to rank coins by size.', longDesc: 'Market capitalization is borrowed from traditional stock markets. Bitcoin\'s market cap first exceeded $1 trillion in February 2021. The total crypto market cap peaked at $3 trillion in November 2021. Fully diluted valuation (FDV) uses total supply instead of circulating supply. Large-cap coins ($10B+): Bitcoin, Ethereum. Mid-cap ($1B-$10B): many Layer 1s. Small-cap (<$1B): altcoins, higher risk/reward. Market cap is important but not the only metric — trading volume, liquidity, and developer activity also matter. A low market cap coin can be manipulated more easily.', related: ['price', 'circulating-supply', 'fdv', 'large-cap', 'small-cap'], coins: ['bitcoin', 'ethereum'] },

  { slug: 'layer-2', term: 'Layer 2 (L2)', category: 'Technology', difficulty: 'Intermediate', definition: 'Layer 2 solutions are built on top of a main blockchain (Layer 1) to improve scalability by processing transactions off-chain and settling on the main chain.', longDesc: 'Layer 2 networks address the blockchain trilemma — the challenge of being simultaneously secure, decentralized, and scalable. Major Ethereum L2s include Arbitrum, Optimism, Base, and zkSync. Rollups are the dominant L2 technology: Optimistic Rollups (Arbitrum, Optimism) assume transactions are valid and challenge fraud; ZK Rollups (zkSync, Starknet) use zero-knowledge proofs to instantly verify transactions. L2s reduce Ethereum gas fees by 10-100x while inheriting Ethereum\'s security. The L2 ecosystem has over $10 billion in total value locked as of 2024.', related: ['ethereum', 'rollup', 'gas-fee', 'scalability', 'arbitrum'], coins: ['ethereum'] },

  { slug: 'yield-farming', term: 'Yield Farming', category: 'Finance', difficulty: 'Advanced', definition: 'Yield farming involves providing liquidity or staking tokens in DeFi protocols to earn rewards — typically in the form of interest, trading fees, or governance tokens.', longDesc: 'Yield farming (also called liquidity mining) became popular in "DeFi Summer" of 2020 when Compound launched COMP token rewards. Farmers move assets between protocols to maximize returns. Annual Percentage Yield (APY) can range from 5% to over 1000% for risky new protocols. Strategies include single-asset staking, liquidity provision, and leveraged farming. Risks include impermanent loss, smart contract exploits, rug pulls, and token inflation eroding rewards. Tools like Yearn Finance automate yield optimization. The highest-risk, highest-reward strategy is farming tokens of newly launched, unaudited protocols.', related: ['defi', 'liquidity-pool', 'apy', 'impermanent-loss', 'staking'], coins: ['uniswap', 'aave', 'compound'] },

  { slug: 'seed-phrase', term: 'Seed Phrase (Recovery Phrase)', category: 'Security', difficulty: 'Beginner', definition: 'A seed phrase is a 12-24 word backup that gives complete access to a crypto wallet. Anyone with your seed phrase can access and steal all your funds — never share it.', longDesc: 'Seed phrases (also called mnemonic phrases) are generated by the BIP-39 standard using a list of 2048 words. They derive all private keys for all cryptocurrency accounts in a hierarchical deterministic (HD) wallet. If your device is lost or broken, your seed phrase is the only way to recover your funds. Store seed phrases: written on paper (laminated), on metal plates, in bank safety deposit boxes — never digitally (no photos, no email, no cloud). Hardware wallets like Ledger generate seed phrases offline for maximum security. About $20 billion in Bitcoin is permanently lost due to lost seed phrases and private keys.', related: ['wallet', 'private-key', 'security', 'cold-storage', 'hardware-wallet'], coins: [] },

  { slug: 'liquidity-pool', term: 'Liquidity Pool', category: 'Finance', difficulty: 'Intermediate', definition: 'A liquidity pool is a smart contract holding pairs of tokens provided by liquidity providers. DEXs use these pools to enable trading without traditional order books.', longDesc: 'Liquidity pools replaced order books in automated market makers (AMMs). Uniswap introduced the constant product formula (x*y=k) for pricing. Liquidity providers (LPs) deposit equal values of two tokens and receive LP tokens representing their share. LPs earn 0.3% of all trades proportional to their share. Impermanent loss occurs when the ratio of pooled tokens changes — LPs may receive less than if they just held the tokens. Concentrated liquidity (Uniswap V3) allows LPs to provide liquidity within specific price ranges, improving capital efficiency by up to 4000x.', related: ['dex', 'amm', 'yield-farming', 'impermanent-loss', 'defi'], coins: ['uniswap'] },

  { slug: 'cold-storage', term: 'Cold Storage', category: 'Security', difficulty: 'Beginner', definition: 'Cold storage means keeping cryptocurrency private keys completely offline — disconnected from the internet — for maximum security against hacks and theft.', longDesc: 'Cold storage is the gold standard for securing large crypto holdings. Methods include hardware wallets (Ledger, Trezor — dedicated devices that never expose private keys to the internet), paper wallets (printed private keys — vulnerable to physical damage), and air-gapped computers (never connected to internet). Exchanges and custodians keep 90-95% of customer funds in cold storage. The 2014 Mt. Gox hack ($450M) and 2022 FTX collapse highlighted the importance of self-custody cold storage. The saying "not your keys, not your coins" emphasizes owning your cold storage wallet.', related: ['wallet', 'seed-phrase', 'hardware-wallet', 'security', 'private-key'], coins: [] },

  { slug: 'bull-market', term: 'Bull Market', category: 'Trading', difficulty: 'Beginner', definition: 'A crypto bull market is a period of sustained price increases, strong investor confidence, and high trading volumes. Bitcoin bull markets typically last 1-2 years.', longDesc: 'Crypto bull markets are characterized by rising prices, increasing adoption, media attention, and new retail investors entering the market. Historically, Bitcoin bull markets follow halvings: 2012→2013 (+8000%), 2016→2017 (+2000%), 2020→2021 (+700%). The "altcoin season" typically follows Bitcoin\'s initial rally, where smaller coins outperform. Fear and Greed Index above 75 indicates "Extreme Greed" common in bull markets. On-chain metrics like exchange outflows, long-term holder accumulation, and NVT ratio signal bull conditions. FOMO (Fear of Missing Out) drives retail participation at market tops.', related: ['bear-market', 'halving', 'altcoin-season', 'fomo', 'market-cycle'], coins: ['bitcoin'] },

  { slug: 'bear-market', term: 'Bear Market', category: 'Trading', difficulty: 'Beginner', definition: 'A crypto bear market is a period of declining prices, negative sentiment, and reduced trading activity. Bitcoin bear markets typically see 70-90% price drops from all-time highs.', longDesc: 'Crypto bear markets (also called "crypto winters") are brutal — Bitcoin has dropped 84% (2018), 77% (2022), and 94% (2014) from peaks. Bear markets typically last 1-2 years. They are characterized by fear, uncertainty, doubt (FUD), exchange collapses, and project failures. However, bears are also the best time to accumulate quality assets at discounts. DCA (Dollar Cost Averaging) during bear markets historically provides excellent returns. The 2022 bear market was triggered by Terra/Luna collapse, Celsius bankruptcy, and FTX fraud. On-chain: exchange inflows, long-term holder distribution, and funding rates signal bear conditions.', related: ['bull-market', 'dca', 'fud', 'capitulation', 'accumulation'], coins: ['bitcoin'] },

  { slug: 'dca', term: 'DCA (Dollar Cost Averaging)', category: 'Trading', difficulty: 'Beginner', definition: 'DCA is an investment strategy where you invest a fixed amount at regular intervals regardless of price — reducing the impact of volatility and avoiding the need to time the market.', longDesc: 'Dollar Cost Averaging is considered one of the safest ways to invest in volatile assets like cryptocurrency. By investing $100 weekly in Bitcoin rather than $5200 all at once, you automatically buy more when prices are low and less when high, averaging out your cost basis. Studies show DCA into Bitcoin over any 4-year period in history has been profitable. Automated DCA services are available on most exchanges and dedicated apps. The opposite strategy — lump sum investing — statistically outperforms DCA in traditional markets but crypto\'s extreme volatility makes DCA more practical for most investors.', related: ['bull-market', 'bear-market', 'accumulation', 'hodl', 'investment-strategy'], coins: ['bitcoin'] },

  { slug: 'hodl', term: 'HODL', category: 'Culture', difficulty: 'Beginner', definition: 'HODL originated from a misspelling of "hold" in a 2013 Bitcoin forum post. It became a crypto cultural term meaning to hold cryptocurrency long-term regardless of price swings.', longDesc: 'The term was born on December 18, 2013, when Bitcoin forum user GameKyuubi posted "I AM HODLING" during a price crash. The typo went viral and became backronymed to "Hold On for Dear Life." HODLers believe in long-term fundamentals over short-term trading. Bitcoin HODLers who bought at any point before 2020 are still in profit despite market volatility. Long-term holders (LTH) are defined on-chain as addresses that haven\'t moved coins in 155+ days. The HODL philosophy opposes active trading, arguing that most traders underperform buy-and-hold strategies due to fees and emotional decisions.', related: ['dca', 'long-term', 'bitcoin', 'bull-market', 'culture'], coins: ['bitcoin'] },
]

// Get all term slugs
export function getAllTermSlugs() {
  return GLOSSARY_TERMS.map(t => ({ term: t.slug }))
}

// Get single term
export function getTerm(slug) {
  return GLOSSARY_TERMS.find(t => t.slug === slug) || null
}

// Get terms by category
export function getTermsByCategory(category) {
  return GLOSSARY_TERMS.filter(t => t.category === category)
}

// Get all categories
export function getAllCategories() {
  return [...new Set(GLOSSARY_TERMS.map(t => t.category))]
}
