#!/usr/bin/env node
// generate.js — CryptoWorld Page Generator
// Run: node generate.js [command]
// Commands: coins, glossary, buy, price, prediction, all, status

const fs = require('fs')
const path = require('path')
const https = require('https')

// ── CONFIG ────────────────────────────────────────────────────────
const CONFIG = {
  siteDir: './src',          // Your Next.js src directory
  coingeckoBase: 'https://api.coingecko.com/api/v3',
  claudeApiKey: process.env.ANTHROPIC_API_KEY || '',  // Optional: for AI descriptions
  maxCoins: 500,             // How many coins to generate pages for
  maxCountries: 30,          // How many countries for buy pages
  batchSize: 10,             // API calls per batch (avoid rate limits)
  delayMs: 2000,             // Delay between batches (ms)
}

// ── COLORS ───────────────────────────────────────────────────────
const c = {
  green:  (t) => `\x1b[32m${t}\x1b[0m`,
  red:    (t) => `\x1b[31m${t}\x1b[0m`,
  yellow: (t) => `\x1b[33m${t}\x1b[0m`,
  blue:   (t) => `\x1b[34m${t}\x1b[0m`,
  bold:   (t) => `\x1b[1m${t}\x1b[0m`,
  dim:    (t) => `\x1b[2m${t}\x1b[0m`,
}

// ── HELPERS ───────────────────────────────────────────────────────
function fetchJSON(url) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { 'Accept': 'application/json', 'User-Agent': 'CryptoWorld/1.0' } }, (res) => {
      let data = ''
      res.on('data', chunk => data += chunk)
      res.on('end', () => {
        try { resolve(JSON.parse(data)) }
        catch(e) { reject(new Error('JSON parse failed: ' + data.slice(0, 100))) }
      })
    }).on('error', reject)
  })
}

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms))
}

function log(emoji, msg, color = 'green') {
  console.log(`${emoji}  ${c[color](msg)}`)
}

function progress(current, total, label) {
  const pct = Math.round((current / total) * 100)
  const bar = '█'.repeat(Math.floor(pct / 5)) + '░'.repeat(20 - Math.floor(pct / 5))
  process.stdout.write(`\r   ${bar} ${pct}% ${c.dim(`(${current}/${total}) ${label}`)}`)
  if (current === total) console.log()
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })
}

function writeFile(filePath, content) {
  ensureDir(path.dirname(filePath))
  fs.writeFileSync(filePath, content, 'utf8')
}

function readJSON(filePath) {
  if (!fs.existsSync(filePath)) return null
  try { return JSON.parse(fs.readFileSync(filePath, 'utf8')) }
  catch { return null }
}

function writeJSON(filePath, data) {
  ensureDir(path.dirname(filePath))
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8')
}

// ── DATA CACHE ────────────────────────────────────────────────────
const CACHE_DIR = './.cache'
const CACHE_FILE = `${CACHE_DIR}/coins.json`

async function getCoinsList(max = 500) {
  const cached = readJSON(CACHE_FILE)
  if (cached && cached.timestamp && Date.now() - cached.timestamp < 3600000) {
    log('💾', `Using cached coin list (${cached.coins.length} coins)`, 'blue')
    return cached.coins
  }

  log('🌐', 'Fetching coin list from CoinGecko...', 'yellow')
  const allCoins = []
  const pages = Math.ceil(max / 250)

  for (let page = 1; page <= pages; page++) {
    try {
      const limit = page === pages ? max % 250 || 250 : 250
      const coins = await fetchJSON(
        `${CONFIG.coingeckoBase}/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=${limit}&page=${page}&sparkline=false`
      )
      allCoins.push(...coins)
      log('✓', `Page ${page}/${pages}: ${coins.length} coins fetched`, 'green')
      if (page < pages) await sleep(CONFIG.delayMs)
    } catch(e) {
      log('⚠', `Page ${page} failed: ${e.message}`, 'yellow')
      break
    }
  }

  writeJSON(CACHE_FILE, { timestamp: Date.now(), coins: allCoins })
  log('💾', `Cached ${allCoins.length} coins`, 'green')
  return allCoins
}

// ── GENERATORS ────────────────────────────────────────────────────

// 1. Update generateStaticParams in coins page
async function generateCoinPages(coins) {
  log('🔄', `Updating coin pages for ${coins.length} coins...`, 'blue')

  const coinPagePath = `${CONFIG.siteDir}/app/coins/[slug]/page.js`
  if (!fs.existsSync(coinPagePath)) {
    log('❌', 'coins/[slug]/page.js not found!', 'red')
    return
  }

  let content = fs.readFileSync(coinPagePath, 'utf8')

  // Build static params list
  const topCoins = coins.slice(0, Math.min(coins.length, 100))
  const coinIds = topCoins.map(c => `'${c.id}'`).join(',\n    ')

  // Replace generateStaticParams
  const newStaticParams = `export async function generateStaticParams() {
  // Auto-generated by generate.js — DO NOT EDIT MANUALLY
  // Generated: ${new Date().toISOString()}
  // Total: ${topCoins.length} coins pre-built, rest via ISR
  const coins = [
    ${coinIds}
  ]
  return coins.map(id => ({ slug: id }))
}`

  // Replace the function
  content = content.replace(
    /export async function generateStaticParams\(\) \{[\s\S]*?\n\}/,
    newStaticParams
  )

  fs.writeFileSync(coinPagePath, content, 'utf8')
  log('✅', `Updated coin page with ${topCoins.length} static params`, 'green')

  // Generate data file for static generation
  const dataPath = `${CONFIG.siteDir}/data/coins.json`
  writeJSON(dataPath, {
    generated: new Date().toISOString(),
    total: coins.length,
    coins: coins.map(c => ({
      id: c.id,
      name: c.name,
      symbol: c.symbol,
      rank: c.market_cap_rank,
      price: c.current_price,
      marketCap: c.market_cap,
      image: c.image,
      change24h: c.price_change_percentage_24h,
    }))
  })
  log('✅', `Saved coins data to src/data/coins.json`, 'green')
}

// 2. Generate buy pages static params
async function generateBuyPages(coins) {
  const COUNTRIES = [
    'pakistan', 'india', 'united-states', 'united-kingdom', 'nigeria',
    'uae', 'turkey', 'brazil', 'indonesia', 'philippines',
    'south-africa', 'canada', 'australia', 'saudi-arabia', 'kenya',
    'ghana', 'egypt', 'malaysia', 'singapore', 'thailand',
    'bangladesh', 'vietnam', 'south-korea', 'japan', 'germany',
    'france', 'spain', 'mexico', 'argentina', 'sri-lanka',
  ]

  const topCoins = coins.slice(0, 50)
  const totalPages = topCoins.length * COUNTRIES.length
  log('🔄', `Generating buy page params: ${topCoins.length} coins × ${COUNTRIES.length} countries = ${totalPages} pages`, 'blue')

  const buyPagePath = `${CONFIG.siteDir}/app/buy/[coin]/[country]/page.js`
  if (!fs.existsSync(buyPagePath)) {
    log('❌', 'buy page not found!', 'red')
    return
  }

  let content = fs.readFileSync(buyPagePath, 'utf8')

  const coinIds = topCoins.map(c => `'${c.id}'`).join(',\n    ')
  const countryIds = COUNTRIES.map(c => `'${c}'`).join(', ')

  const newStaticParams = `export async function generateStaticParams() {
  // Auto-generated by generate.js — ${new Date().toISOString()}
  // ${totalPages} pages total
  const topCoins = [
    ${coinIds}
  ]
  const countries = [${countryIds}]
  const params = []
  for (const coin of topCoins) {
    for (const country of countries) {
      params.push({ coin, country })
    }
  }
  return params
}`

  content = content.replace(
    /export async function generateStaticParams\(\) \{[\s\S]*?\n\}/,
    newStaticParams
  )

  fs.writeFileSync(buyPagePath, content, 'utf8')
  log('✅', `Buy pages: ${totalPages} static params updated`, 'green')
}

// 3. Generate price pages
async function generatePricePages(coins) {
  const CURRENCIES = ['pkr', 'inr', 'aed', 'sar', 'gbp', 'eur', 'try', 'brl', 'jpy', 'cad', 'aud', 'myr']
  const topCoins = coins.slice(0, 100)
  const totalPages = topCoins.length * CURRENCIES.length

  log('🔄', `Price pages: ${topCoins.length} coins × ${CURRENCIES.length} currencies = ${totalPages} pages`, 'blue')

  const pricePagePath = `${CONFIG.siteDir}/app/price/[coin]/[currency]/page.js`
  if (!fs.existsSync(pricePagePath)) {
    log('❌', 'price page not found!', 'red')
    return
  }

  let content = fs.readFileSync(pricePagePath, 'utf8')
  const coinIds = topCoins.map(c => `'${c.id}'`).join(',\n    ')

  const newStaticParams = `export async function generateStaticParams() {
  // Auto-generated by generate.js — ${new Date().toISOString()}
  const topCoins = [
    ${coinIds}
  ]
  const currencies = ${JSON.stringify(CURRENCIES)}
  const params = []
  for (const coin of topCoins) {
    for (const currency of currencies) {
      params.push({ coin, currency })
    }
  }
  return params
}`

  content = content.replace(
    /export async function generateStaticParams\(\) \{[\s\S]*?\n\}/,
    newStaticParams
  )

  fs.writeFileSync(pricePagePath, content, 'utf8')
  log('✅', `Price pages: ${totalPages} static params updated`, 'green')
}

// 4. Generate prediction pages
async function generatePredictionPages(coins) {
  const YEARS = ['2025', '2026', '2027', '2028', '2029', '2030', '2035', '2040']
  const topCoins = coins.slice(0, 100)
  const totalPages = topCoins.length * YEARS.length

  log('🔄', `Prediction pages: ${topCoins.length} coins × ${YEARS.length} years = ${totalPages} pages`, 'blue')

  const predPagePath = `${CONFIG.siteDir}/app/prediction/[coin]/[year]/page.js`
  if (!fs.existsSync(predPagePath)) {
    log('❌', 'prediction page not found!', 'red')
    return
  }

  let content = fs.readFileSync(predPagePath, 'utf8')
  const coinIds = topCoins.map(c => `'${c.id}'`).join(',\n    ')

  const newStaticParams = `export async function generateStaticParams() {
  // Auto-generated by generate.js — ${new Date().toISOString()}
  const topCoins = [
    ${coinIds}
  ]
  const YEARS = ${JSON.stringify(YEARS)}
  return topCoins.flatMap(coin => YEARS.map(year => ({ coin, year })))
}`

  content = content.replace(
    /export async function generateStaticParams\(\) \{[\s\S]*?\n\}/,
    newStaticParams
  )

  fs.writeFileSync(predPagePath, content, 'utf8')
  log('✅', `Prediction pages: ${totalPages} static params updated`, 'green')
}

// 5. Generate compare pages
async function generateComparePages(coins) {
  const topCoins = coins.slice(0, 20)
  const pairs = []

  // Generate all combinations
  for (let i = 0; i < topCoins.length; i++) {
    for (let j = i + 1; j < topCoins.length; j++) {
      pairs.push(`${topCoins[i].id}-vs-${topCoins[j].id}`)
    }
  }

  log('🔄', `Compare pages: ${pairs.length} pairs from top 20 coins`, 'blue')

  const comparePath = `${CONFIG.siteDir}/app/compare/[pair]/page.js`
  if (!fs.existsSync(comparePath)) {
    log('❌', 'compare page not found!', 'red')
    return
  }

  let content = fs.readFileSync(comparePath, 'utf8')
  const pairsList = pairs.map(p => `'${p}'`).join(',\n    ')

  const newStaticParams = `export async function generateStaticParams() {
  // Auto-generated by generate.js — ${new Date().toISOString()}
  // ${pairs.length} comparison pairs
  const topPairs = [
    ${pairsList}
  ]
  return topPairs.map(pair => ({ pair }))
}`

  content = content.replace(
    /export async function generateStaticParams\(\) \{[\s\S]*?\n\}/,
    newStaticParams
  )

  fs.writeFileSync(comparePath, content, 'utf8')
  log('✅', `Compare pages: ${pairs.length} pairs updated`, 'green')
}

// 6. Generate sitemap
async function generateSitemap(coins) {
  log('🔄', 'Generating sitemap...', 'blue')

  const BASE = process.env.NEXT_PUBLIC_SITE_URL || 'https://your-domain.com'
  const COUNTRIES = ['pakistan','india','united-states','united-kingdom','nigeria','uae','turkey','brazil','indonesia','philippines','south-africa','canada','australia','saudi-arabia','kenya','ghana','egypt','malaysia','singapore','thailand','bangladesh','vietnam','south-korea','japan','germany','france','spain','mexico','argentina','sri-lanka']
  const CURRENCIES = ['pkr','inr','aed','sar','gbp','eur','try','brl','jpy','cad','aud','myr']
  const YEARS = ['2025','2026','2027','2028','2029','2030','2035','2040']

  const urls = [`${BASE}`, `${BASE}/trending`, `${BASE}/glossary`, `${BASE}/about`]

  // Coin pages
  coins.forEach(c => urls.push(`${BASE}/coins/${c.id}`))

  // Buy pages (top 50)
  coins.slice(0, 50).forEach(c => {
    COUNTRIES.forEach(country => urls.push(`${BASE}/buy/${c.id}/${country}`))
  })

  // Price pages (top 100)
  coins.slice(0, 100).forEach(c => {
    CURRENCIES.forEach(cur => urls.push(`${BASE}/price/${c.id}/${cur}`))
  })

  // Prediction pages (top 100)
  coins.slice(0, 100).forEach(c => {
    YEARS.forEach(year => urls.push(`${BASE}/prediction/${c.id}/${year}`))
  })

  // Compare pages (top 20)
  const top20 = coins.slice(0, 20)
  for (let i = 0; i < top20.length; i++) {
    for (let j = i + 1; j < top20.length; j++) {
      urls.push(`${BASE}/compare/${top20[i].id}-vs-${top20[j].id}`)
    }
  }

  log('✅', `Sitemap: ${urls.length.toLocaleString()} URLs generated`, 'green')

  // Write URL list for reference
  writeFile('.cache/sitemap-urls.txt', urls.join('\n'))
  log('✅', `URLs saved to .cache/sitemap-urls.txt`, 'green')

  return urls.length
}

// 7. Show status
function showStatus() {
  console.log('\n' + c.bold('═'.repeat(50)))
  console.log(c.bold('  📊 CryptoWorld Page Status'))
  console.log(c.bold('═'.repeat(50)))

  const checks = [
    ['src/app/coins/[slug]/page.js', 'Coin pages'],
    ['src/app/buy/[coin]/[country]/page.js', 'Buy pages'],
    ['src/app/price/[coin]/[currency]/page.js', 'Price pages'],
    ['src/app/prediction/[coin]/[year]/page.js', 'Prediction pages'],
    ['src/app/compare/[pair]/page.js', 'Compare pages'],
    ['src/app/glossary/[term]/page.js', 'Glossary pages'],
    ['src/app/trending/page.js', 'Trending page'],
    ['src/lib/coingecko.js', 'CoinGecko API lib'],
    ['src/lib/glossary.js', 'Glossary data'],
    ['src/lib/countries.js', 'Countries data'],
    ['src/components/SearchBar.js', 'Search bar'],
    ['src/components/PriceChart.js', 'Price chart'],
    ['src/components/NewsSection.js', 'News section'],
  ]

  checks.forEach(([file, label]) => {
    const exists = fs.existsSync(file)
    console.log(`  ${exists ? c.green('✓') : c.red('✗')}  ${label} ${c.dim(`(${file})`)}`)
  })

  // Count static params
  const coinPage = fs.existsSync('src/app/coins/[slug]/page.js')
    ? fs.readFileSync('src/app/coins/[slug]/page.js', 'utf8')
    : ''
  const coinCount = (coinPage.match(/'[\w-]+'/g) || []).length

  console.log('\n' + c.bold('  📈 Page Estimates:'))

  const cached = readJSON('.cache/coins.json')
  if (cached) {
    const n = cached.coins.length
    console.log(`  ${c.green('●')} Coin pages:       ${c.bold(Math.min(n, 100).toString())} pre-built, ${c.bold(n.toString())} via ISR`)
    console.log(`  ${c.green('●')} Buy pages:        ${c.bold((Math.min(n, 50) * 30).toLocaleString())} (50 coins × 30 countries)`)
    console.log(`  ${c.green('●')} Price pages:      ${c.bold((Math.min(n, 100) * 12).toLocaleString())} (100 coins × 12 currencies)`)
    console.log(`  ${c.green('●')} Prediction pages: ${c.bold((Math.min(n, 100) * 8).toLocaleString())} (100 coins × 8 years)`)
    console.log(`  ${c.green('●')} Compare pages:    ${c.bold('190')} (top 20 coins combinations)`)
    console.log(`  ${c.green('●')} Glossary:         64 terms`)
    const total = Math.min(n, 100) + (Math.min(n, 50) * 30) + (Math.min(n, 100) * 12) + (Math.min(n, 100) * 8) + 190 + 64
    console.log(`  ${c.bold('TOTAL:')}             ${c.green(c.bold(total.toLocaleString() + ' pages'))}`)
  }

  console.log('\n  ' + c.bold('🚀 Commands:'))
  console.log('  ' + c.dim('node generate.js all         ') + '→ Generate everything')
  console.log('  ' + c.dim('node generate.js coins       ') + '→ Update coin pages only')
  console.log('  ' + c.dim('node generate.js buy         ') + '→ Update buy pages only')
  console.log('  ' + c.dim('node generate.js price       ') + '→ Update price pages only')
  console.log('  ' + c.dim('node generate.js prediction  ') + '→ Update prediction pages only')
  console.log('  ' + c.dim('node generate.js compare     ') + '→ Update compare pages only')
  console.log('  ' + c.dim('node generate.js sitemap     ') + '→ Generate sitemap')
  console.log('  ' + c.dim('node generate.js deploy      ') + '→ Git commit + push')
  console.log('  ' + c.dim('node generate.js status      ') + '→ Show this status')
  console.log('')
}

// 8. Git deploy
async function deploy(message = 'Auto update pages') {
  const { execSync } = require('child_process')
  log('🚀', 'Deploying to GitHub...', 'blue')

  try {
    execSync('git add .', { stdio: 'inherit' })
    execSync(`git commit -m "${message} - ${new Date().toLocaleDateString()}"`, { stdio: 'inherit' })
    execSync('git push origin main', { stdio: 'inherit' })
    log('✅', 'Deployed! Vercel will auto-redeploy in 1-2 minutes', 'green')
  } catch(e) {
    log('⚠', 'Git push failed — may already be up to date', 'yellow')
  }
}

// ── MAIN ──────────────────────────────────────────────────────────
async function main() {
  const command = process.argv[2] || 'status'

  console.log('\n' + c.bold(c.blue('🦎 CryptoWorld Page Generator')))
  console.log(c.dim('   Automated page generation system\n'))

  if (command === 'status') {
    showStatus()
    return
  }

  if (command === 'deploy') {
    const msg = process.argv[3] || 'Auto update'
    await deploy(msg)
    return
  }

  // Fetch coins for generation
  const coins = await getCoinsList(CONFIG.maxCoins)
  console.log(c.green(`\n✓ ${coins.length} coins loaded\n`))

  const startTime = Date.now()

  if (command === 'all' || command === 'coins') {
    await generateCoinPages(coins)
  }
  if (command === 'all' || command === 'buy') {
    await generateBuyPages(coins)
  }
  if (command === 'all' || command === 'price') {
    await generatePricePages(coins)
  }
  if (command === 'all' || command === 'prediction') {
    await generatePredictionPages(coins)
  }
  if (command === 'all' || command === 'compare') {
    await generateComparePages(coins)
  }
  if (command === 'all' || command === 'sitemap') {
    await generateSitemap(coins)
  }

  const elapsed = ((Date.now() - startTime) / 1000).toFixed(1)

  console.log('\n' + c.bold('═'.repeat(50)))
  console.log(c.green(c.bold(`  ✅ Done in ${elapsed}s`)))

  if (command === 'all') {
    const total = coins.length + (50 * 30) + (100 * 12) + (100 * 8) + 190 + 64
    console.log(c.green(`  📄 ~${total.toLocaleString()} pages configured`))
    console.log(c.dim('\n  Now run: node generate.js deploy'))
  }
  console.log(c.bold('═'.repeat(50)) + '\n')
}

main().catch(e => {
  console.error(c.red('\n❌ Error: ' + e.message))
  process.exit(1)
})
